export const LOGIN = "login"
export const LOGOUT = "logout"
export const SETSONG = "setSong"
export const SETLIST = "setList"
export const SETINDEX = "setIndex"
export const ADDHISTORY = "addHistory"
export const CLEARHISTORY = "clearHistory"
export const POPHISTORY = "popHistory"
